"""Fluxo real no Chrome, com servidor local em execução."""
import json
import os
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'test-results'
SHOTS=ROOT.parent/'documentacao/imagens'
OUT.mkdir(exist_ok=True);SHOTS.mkdir(parents=True,exist_ok=True)
checks=[]
with sync_playwright() as p:
    browser=p.chromium.launch(channel='chrome',headless=True)
    page=browser.new_page(viewport={'width':1440,'height':1000})
    errors=[]
    page.on('pageerror',lambda error:errors.append(str(error)))
    def click(name): page.get_by_role('button',name=name,exact=True).click()
    def fill(name,value): page.locator('#field-'+name).fill(value)
    def select(name,value): page.locator('#field-'+name).select_option(value)
    def shot(name): page.screenshot(path=str(SHOTS/name),full_page=True)
    page.goto(os.environ.get('ECOGESTAO_TEST_URL','http://127.0.0.1:8000'));shot('01_acesso.png')
    page.locator('#email').fill('gestor@demo.local');page.locator('#password').fill('EcoDemo2026!');click('Entrar')
    expect(page.locator('#content')).to_contain_text('4.280')
    expect(page.locator('#filter-start')).to_have_value('01/09/2026')
    expect(page.locator('#filter-end')).to_have_value('30/09/2026')
    page.locator('#filter-start').fill('31/02/2026');click('Aplicar filtros')
    expect(page.locator('#notice')).to_contain_text('data válida')
    page.locator('#filter-start').fill('01/09/2026');click('Aplicar filtros')
    expect(page.locator('#content')).to_contain_text('4.280')
    assert page.locator('body').evaluate('(el) => getComputedStyle(el).fontFamily').startswith('Inter')
    assert page.evaluate("Array.from(document.fonts).some(font => font.family === 'Inter' && font.status === 'loaded')")
    shot('02_painel.png')
    checks.append('Login real e painel com totais esperados')
    click('Setores');click('Novo registro');fill('name','Setor E2E');click('Salvar')
    expect(page.locator('#content')).to_contain_text('Setor E2E')
    checks.append('Cadastro de setor pela interface')
    click('Parceiros');click('Novo registro');fill('name','Parceiro E2E');fill('contact','Contato demonstrativo');click('Salvar')
    expect(page.locator('#content')).to_contain_text('Parceiro E2E')
    checks.append('Cadastro de parceiro pela interface')
    click('Registros ambientais');click('Novo registro');select('metric','residuos')
    expect(page.locator('#field-date')).to_have_attribute('placeholder','DD/MM/AAAA')
    fill('date','20/09/2026');fill('quantity','7.5')
    page.locator('#field-sector_id').select_option(label='Setor E2E')
    page.locator('#field-partner_id').select_option(label='Parceiro E2E')
    fill('waste_type','Papel de teste');fill('destination','Reciclagem');fill('note','Registro criado no teste do navegador');click('Salvar')
    expect(page.locator('#content')).to_contain_text('Papel de teste');shot('03_registros.png')
    checks.append('Registro real de resíduos com vínculos')
    click('Metas');click('Novo registro');fill('title','Meta E2E de resíduos');select('metric','residuos')
    page.locator('#field-sector_id').select_option(label='Setor E2E')
    fill('start_date','01/09/2026');fill('end_date','30/09/2026');fill('limit_value','10');click('Salvar')
    expect(page.locator('#content')).to_contain_text('7,5 / 10 kg');shot('04_metas.png')
    checks.append('Meta calculada com os dados persistidos')
    click('Ações corretivas');click('Novo registro');fill('title','Ação E2E');fill('description','Verificar separação do material coletado.')
    page.locator('#field-sector_id').select_option(label='Setor E2E')
    fill('due_date','25/09/2026');click('Salvar')
    row=page.locator('tr').filter(has_text='Ação E2E');expect(row).to_be_visible()
    row.get_by_role('button',name='Editar').click();select('status','concluida');fill('evidence','Inspeção concluída e segregação conferida no teste.');click('Salvar')
    expect(row).to_contain_text('Concluída');shot('05_acoes.png')
    checks.append('Ação criada e concluída com evidência')
    click('Relatórios');page.locator('#filter-sector').select_option(label='Setor E2E');click('Aplicar filtros')
    expect(page.locator('tbody tr')).to_have_count(1)
    with page.expect_download() as info: click('Baixar CSV')
    target=OUT/'navegador_registros.csv';info.value.save_as(target)
    assert 'Papel de teste' in target.read_text(encoding='utf-8-sig')
    checks.append('Filtro e download CSV pelo navegador');shot('06_relatorio.png')
    click('Histórico');expect(page.locator('#content')).to_contain_text('criar')
    checks.append('Histórico consultado pelo gestor')
    click('Serviços e API');expect(page.locator('#content')).to_contain_text('/api/records')
    checks.append('Contrato gerado pela API em execução')
    click('Sair');page.locator('#email').fill('consulta@demo.local');page.locator('#password').fill('EcoDemo2026!');click('Entrar')
    expect(page.locator('#app')).to_be_visible();click('Registros ambientais')
    expect(page.get_by_role('button',name='Novo registro',exact=True)).to_have_count(0)
    expect(page.get_by_role('button',name='Histórico',exact=True)).to_be_hidden()
    checks.append('Consulta sem controles de alteração')
    page.set_viewport_size({'width':390,'height':844})
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
    checks.append('Layout móvel sem transbordamento horizontal')
    assert not errors,errors
    browser.close()
(OUT/'browser.json').write_text(json.dumps({'passed':len(checks),'checks':checks,'javascript_errors':errors},ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps({'passed':len(checks),'checks':checks},ensure_ascii=False))
